# Generated by Django 5.2.9 on 2025-12-07 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        help_text="Data e horário da consulta",
                        verbose_name="Data da Consulta",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "professional",
                    models.ForeignKey(
                        help_text="Profissional de saúde responsável pela consulta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="professionals.professional",
                        verbose_name="Profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consulta",
                "verbose_name_plural": "Consultas",
                "ordering": ["-date"],
            },
        ),
    ]
