# Generated by Django 5.2.9 on 2025-12-07 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Professional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_name",
                    models.CharField(
                        help_text="Nome social do profissional",
                        max_length=255,
                        verbose_name="Nome Social",
                    ),
                ),
                (
                    "profession",
                    models.CharField(
                        help_text="Ocupação profissional (ex: Médico, Enfermeiro, Psicólogo)",
                        max_length=255,
                        verbose_name="Profissão",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        help_text="Endereço completo do profissional",
                        verbose_name="Endereço",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Profissional",
                "verbose_name_plural": "Profissionais",
                "ordering": ["social_name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("mobile", "Celular"),
                            ("phone", "Telefone"),
                            ("email", "E-mail"),
                            ("linkedin", "LinkedIn"),
                        ],
                        help_text="Tipo de contato (whatsapp, celular, telefone, e-mail, linkedin)",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Valor do contato (número, endereço de e-mail, URL, etc.)",
                        max_length=255,
                        verbose_name="Valor",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "professional",
                    models.ForeignKey(
                        help_text="Profissional de saúde associado ao contato",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="professionals.professional",
                        verbose_name="Profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contato",
                "verbose_name_plural": "Contatos",
                "ordering": ["kind"],
            },
        ),
    ]
