# Generated by Django 5.2.9 on 2025-12-08 02:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professional",
            name="address",
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Nome da rua/logradouro",
                        max_length=255,
                        verbose_name="Rua",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True,
                        help_text="Número do endereço",
                        max_length=255,
                        null=True,
                        verbose_name="Número",
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        blank=True,
                        help_text="Bairro",
                        max_length=255,
                        null=True,
                        verbose_name="Bairro",
                    ),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True,
                        help_text="Complemento do endereço (ex: Apto 101, Bloco B)",
                        max_length=255,
                        null=True,
                        verbose_name="Complemento",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        help_text="Nome da cidade",
                        max_length=255,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        help_text="Nome ou sigla do estado",
                        max_length=255,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        help_text="CEP com 8 dígitos (apenas números)",
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CEP deve conter exatamente 8 dígitos numéricos.",
                                regex="^\\d{8}$",
                            )
                        ],
                        verbose_name="CEP",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "professional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="professionals.professional",
                        verbose_name="Profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
                "ordering": ["street"],
            },
        ),
    ]
