# Generated by Django 5.2.9 on 2025-12-08 02:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("professionals", "0002_remove_professional_address_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="professional",
            name="uuid",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
